repos:
- repo: local
  hooks:
  - id: ruff
    name: Linter
    language: system
    entry: poetry run ruff check
    types: [file, python]
  - id: mypy
    name: Type checker
    language: system
    entry: poetry run mypy
    types: [file, python]
